{
	"vue-empty": {
		"scope": "vue",
		"prefix": "vuempty",
		"body": [
			"<template>",
			"  <div>",
			"     {{ }}",
			"  </div>",
			"</template>",
			"",
			"<script>",
			"import { mapGetters } from 'vuex'",
			"export default {",
			"  name: '$1',",
			"  props: {},",
			"  data() {",
			"    return {",
			"      $2",
			"    }",
			"  },",
			"  computed: {",
			"    ...mapGetters({",
			"      $3: '$4',",
			"    }),",
			"  }",
			"  methods: {",
			"    //load projects from API to Store",
			"    //async loadProperties() {",
			"    //  await this.\$store.dispatch('myprop/load')",
			"    //}",
			"  },",
			"  mounted() {",
			"    //if empty projectlist, the load from API",
			"    //if (this.myprop.length == 0) {",
			"    //  this.loadProperties()",
			"    //}",
			"  }",
			"}",
			"</script>",
			"<style scoped>",
			"",
			"</style>"
		],
		"description": "empty vuejs component"
	}
}
